### ISSUE TITLE
Problem with docker deploy

### ISSUE THREAD

**Issue by apardo** [d-cent/objective8#3]
Hello, I have a problem with Docker deployment. When I run the containers the port 8080/tcp rejects connections. nginx message is '502 Bad Gateway'.

The log says:

root@objective8:~# docker logs 019bd7ae2c12
2016/05/16 14:46:06 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.25, server: objective8.podemos.info, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8080/", host: "objective8.podemos.info"
2016/05/16 14:46:06 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.25, server: objective8.podemos.info, request: "GET / HTTP/1.1", upstream: "http://[::1]:8080/", host: "objective8.podemos.info"
10.0.0.25 - - [16/May/2016:14:46:06 +0000] "GET / HTTP/1.1" 502 575 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
2016/05/16 14:46:06 [error] 6#6: *4 no live upstreams while connecting to upstream, client: 10.0.0.25, server: objective8.podemos.info, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "objective8.podemos.info", referrer: "https://objective8.podemos.info/"
10.0.0.25 - - [16/May/2016:14:46:06 +0000] "GET /favicon.ico HTTP/1.1" 502 575 "https://objective8.podemos.info/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
2016/05/16 14:48:47 [error] 6#6: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.25, server: objective8.podemos.info, request: "GET / HTTP/1.1", upstream: "http://[::1]:8080/", host: "objective8.podemos.info"
2016/05/16 14:48:47 [error] 6#6: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.25, server: objective8.podemos.info, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8080/", host: "objective8.podemos.info"
10.0.0.25 - - [16/May/2016:14:48:47 +0000] "GET / HTTP/1.1" 502 575 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
2016/05/16 14:48:47 [error] 6#6: *8 no live upstreams while connecting to upstream, client: 10.0.0.25, server: objective8.podemos.info, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "objective8.podemos.info", referrer: "https://objective8.podemos.info/"
10.0.0.25 - - [16/May/2016:14:48:47 +0000] "GET /favicon.ico HTTP/1.1" 502 575 "https://objective8.podemos.info/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"

And these are the ports that are open, it seems that there is nothing listening on port 7000/tcp:

root@objective8:~# netstat -tanup
Conexiones activas de Internet (servidores y establecidos)
Proto  Recib Enviad Dirección local         Dirección remota       Estado       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:\*               ESCUCHAR    559/sshd
tcp        0    428 10.0.0.53:22            79.145.114.4:49811      ESTABLECIDO 4135/1
tcp6       0      0 :::80                   :::\*                    ESCUCHAR    2964/docker-proxy
tcp6       0      0 :::8080                 :::\*                    ESCUCHAR    2775/docker-proxy
tcp6       0      0 :::8081                 :::\*                    ESCUCHAR    2767/docker-proxy
tcp6       0      0 :::22                   :::\*                    ESCUCHAR    559/sshd
tcp6       0      0 :::443                  :::\*                    ESCUCHAR    2956/docker-proxy
tcp6       0      0 127.0.0.1:8080          127.0.0.1:42795         TIME_WAIT   -
udp        0      0 0.0.0.0:68              0.0.0.0:\*                           504/dhclient
udp        0      0 0.0.0.0:38119           0.0.0.0:\*                           504/dhclient
udp6       0      0 :::58940

What can I be doing wrong to launch the service?

Thanks

**Comment by Seraphiana** [comment]
Hi Antonio,

Is this the logs for nginx? At a hunch it looks like a problem with the connection between objective8 and nginx, possibly due to a mistake in your nginx.conf file. Can you send the logs for objective8 as well?

Objective8 doesn't use port 7000, its used for our other service, Coracle. It looks like you might have something else running on port 8080 at that address, is this the case?

**Comment by apardo** [comment]
This is the nginx config:

root@objective8:~# cat /etc/nginx/nginx.conf
events {
}
http {
  server {
  listen 80;
  server_name objective8.podemos.info;
    # trailing '/' after port means app doesn't know about '/as2/'
    location /as2/ {
      proxy_pass http://localhost:7000/;
    }
    # no trailing '/' after port means app knows about '/api/v1/'
    location /api/v1/ {
      proxy_pass http://localhost:8081;
    }
    location / {
      proxy_pass http://localhost:8080;
    }
  }

}

I attach the logs of objective8.

Thanks

[stderr.log.txt](https://github.com/d-cent/objective8/files/266410/stderr.log.txt)
[stdout.log.txt](https://github.com/d-cent/objective8/files/266411/stdout.log.txt)

**Comment by apardo** [comment]
We have a SSL proxy that redirect the HTTPS traffic to our port 80.

**Comment by Seraphiana** [comment]
It looks like you've got empty values in your objective8 config file, and possibly that you're using the wrong template. 
To deploy using docker you need to copy and fill in the objective8_docker_config_template file rather than the objective8_config_template file, removing or commenting out any values that aren't set.

**Comment by apardo** [comment]
The same problem. This is the template I'm using:

root@objective8:~/objective8# cat ops/objective8_docker_config_template
BASE_URI=objective8.podemos.info
POSTGRES_DB=objective8
POSTGRES_USER=objective8
POSTGRES_PASSWORD=objective8
APP_NAME=objective8

**Comment by Seraphiana** [comment]
Hmmm. What output do you get from running _docker logs objective8_?

**Comment by apardo** [comment]
[stderr.log.txt](https://github.com/d-cent/objective8/files/266485/stderr.log.txt)
[stdout.log.txt](https://github.com/d-cent/objective8/files/266486/stdout.log.txt)

**Comment by Seraphiana** [comment]
ok, that's a bit more informative now. Can you stop, remove and restart postgres with the new config file, then stop remove and restart objective8, then stop remove and restart nginx?

**Comment by apardo** [comment]
Now the application starts but it respond with: 503 Service Unavailable.

I attach the objective8 logs
[stderr.log.txt](https://github.com/d-cent/objective8/files/268065/stderr.log.txt)
[stdout.log.txt](https://github.com/d-cent/objective8/files/268066/stdout.log.txt)

**Comment by apardo** [comment]
Now the application starts, thanks. But now, how can I create an user?

**Comment by Seraphiana** [comment]
You'll need to configure sign in, and then you should be good to go. Were you planning on using facebook or twitter?

for facebook you'll need to make a new app [here](https://developers.facebook.com/)

for twitter you'll need to do same [here](https://apps.twitter.com/app/new)

more details are in the config.md file. It looks like you have private mode enabled, though, which will only work with stonecutter log in.
